services:

  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432

  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - 6379:6379

volumes:
  db-config: