services:

  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432

volumes:
  db-config: