---
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Run Pre-Commit
        run: pnpm turbo run check-types format:ci